modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gam"
version = "1.20.1-0.1.0"
displayName = "Genesis: Addon"
authors = "MrEskimo"
description = '''
Adds more planets to genesis
'''

[[dependencies.gam]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gam]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gam]]
modId = "genesis"
mandatory = true
versionRange = "[1.20.1-0.6.0,)"
ordering = "NONE"
side = "BOTH"
